### ISSUE TITLE
8 Story Points - 2.1 Search by name

### ISSUE THREAD

**Issue by ocollison** [CSBSJU-CS330-F21/CSB-SJU-Student-Services#10]
As a buyer, I wish to search for the specific product/service I need through a search tab
## Tasks
- [ ] add a search bar on the main page
- [ ] add the ability for the search bar to reproduce all listings with any keywords you typed in
- [ ] add ability to search by tags
- [ ] add JUnit testing

**Comment by BMURRAY002** [comment]
When implemented, the search bar will be a text box at the top of the page which will allow a user to find a listing based on the key words they entered.
