### ISSUE TITLE
3 Story Points - 1.11 Confirm Delete Product

### ISSUE THREAD

**Issue by kaylithulin** [CSBSJU-CS330-F21/CSB-SJU-Student-Services#117]
As a seller, I want to be able to delete my saved products, so that I can get rid of unwanted products

## Tasks
- [ ] Add a confirm button
- [ ] after hitting the delete button
- [ ] erase product from database

## Done Criteria 
When the seller hits the delete button, a confirm button is showed before permanently deleting product.
