### ISSUE TITLE
5 Story Points - 9.2 Filters 

### ISSUE THREAD

**Issue by jlindsey001** [CSBSJU-CS330-F21/CSB-SJU-Student-Services#12]
As a buyer, I want to search services by category so that I will be able to find the right service.
## Tasks
- [ ] add a dropdown menu on page with different categories you can select to view listings off
- [ ] make it so that you can include multiple categories in your search to view listings off
- [ ] add ability to filter by tags
