### ISSUE TITLE
3 Story Points - 13.1 - Account Page

### ISSUE THREAD

**Issue by dennisd001** [CSBSJU-CS330-F21/CSB-SJU-Student-Services#136]
As a user I want to see my account information so that I can share my information to others
## Done criteria
User is able to access page with their username, first name and last name.
## Tasks
- [ ] add user's information from the database
- [ ] add page with user's account information
- [ ] add button on main page to access account page
- [ ] add JUnit testing of user favorites
