### ISSUE TITLE
5 Story Points - 6.1 Favorite page

### ISSUE THREAD

**Issue by bluebous** [CSBSJU-CS330-F21/CSB-SJU-Student-Services#14]
As a user I want to view the listings I have favorited so that I can easily access them later
## Done criteria
User is able to access page with a list of all their favorite listings
## Tasks
- [ ] add table of user favorites to database
- [ ] add page with user favorite listings
- [ ] add button on main page to access favorite's page
- [ ] add JUnit testing of user favorites
