### ISSUE TITLE
5 Story Points - 6.2 Favorite button 

### ISSUE THREAD

**Issue by bluebous** [CSBSJU-CS330-F21/CSB-SJU-Student-Services#15]
As a user I want to favorite listings I like so that I can find them easier
## Tasks
- [x] Have a Favorite button on listings
- [ ] Add a personal favorite List that holds listings for users
- [ ] Have the favorite button add the listing entity to the user's favorite list
## Done Criteria
The seller is able to favorite a listing and able to find it on their favorite page
