### ISSUE TITLE
5 Story Points - 1.2 View Products 

### ISSUE THREAD

**Issue by kaylithulin** [CSBSJU-CS330-F21/CSB-SJU-Student-Services#17]
As a seller, I want to view my products that are created so that I have the option to change if I need. #1 
## Tasks
- [ ] add a Listings page for sellers
- [ ] on that page they can see a table of their posted listing
- [ ] add an option to view listing on the table which displays the listing
- [ ] saves changes
- [ ] add tests to JUnit

## Done Criteria 
the seller can successfully view added products to table and view the listing page
