### ISSUE TITLE
20 Story Points - 1.3 Listing Image

### ISSUE THREAD

**Issue by dennisd001** [CSBSJU-CS330-F21/CSB-SJU-Student-Services#18]
As a seller, I would like to be given the option to upload an image so buyers can understand or see my product/service
## Done Criteria:
user is able to upload image when posting their listing and the image displays under the listing
## Tasks
- [x] #79
- [x] add an option to upload an image in the create listing section
- [ ] have that image able seen by users in its' listing when finalized and published
- [ ] add tests to make sure feature is working correctly
