### ISSUE TITLE
13 Story Points - 1.4 Adding Service/Product Description

### ISSUE THREAD

**Issue by jlindsey001** [CSBSJU-CS330-F21/CSB-SJU-Student-Services#21]
As a user, I want to be able to add a description to my service or product so that I can inform people who see my listing.
## Done Criteria:
Users of the website can successfully add a description to their listing, whether it be a product or service.
## Tasks
- [x] #85
- [x] add a description box in the Create Listing Functionality
- [x] be able to type my description of the product
- [x] the description I typed is then posted with the created listing after finalization 
- [x] add tests to JUint
