### ISSUE TITLE
3 Story point - 3.9 Log out interface

### ISSUE THREAD

**Issue by jlindsey001** [CSBSJU-CS330-F21/CSB-SJU-Student-Services#30]
As a user, i want to be able to log out of my account so that I can navigate between different accounts.
## Done Criteria:
when user log out their session is ended and they no longer can access their profile until they login again
## Tasks
- [ ] Have Button on main page
- [ ] button brings you to log out page
- [ ] text box says log out
- [ ] button that logs you out and brings you to Log in page
