### ISSUE TITLE
3.5 Log in backend

### ISSUE THREAD

**Issue by kaylithulin** [CSBSJU-CS330-F21/CSB-SJU-Student-Services#33]
As a user, I want my account to be authenticated, so that I can access my account

## Done Criteria
when a user attempts to log in to their account, their username and password is checked if it's valid. 

## Tasks
- [ ] Gets users info from database
- [ ] server checks username 
- [ ] server checks password
- [ ] sends valid or invalid response to browser
