### ISSUE TITLE
3.7 Sign up Backend

### ISSUE THREAD

**Issue by kaylithulin** [CSBSJU-CS330-F21/CSB-SJU-Student-Services#34]
#3 As a user, I want to create an account so that I can access the website

## Done Criteria
When the user signs up it saves their information of created account and allows them access to website

## Tasks
- [x] create UML use case diagram
- [x] write test cases
- [x] server saves username
- [x] server saves password
- [x] sends confirmation to browser
