### ISSUE TITLE
11.1 Email Notifications

### ISSUE THREAD

**Issue by ocollison** [CSBSJU-CS330-F21/CSB-SJU-Student-Services#5]
As a seller, I want to be able to enable email-push notification when I am contacted on the app so that I can respond promptly

## Tasks
- [ ] select email service (send grid?)
- [ ] add trigger to sent messages to send email
- [ ] send email request when trigger is activated
- [ ] design Notification email template

## Done Criteria
user successfully receives email in their inbox when contacted by another user.
