### ISSUE TITLE
3.8 Sign up over write

### ISSUE THREAD

**Issue by kaylithulin** [CSBSJU-CS330-F21/CSB-SJU-Student-Services#53]
#3 
As a User, I want to have a unique username so that no one else has it.
## Done Criteria
The database sends an error to the sign up page when someone enters a username already saved in the database

## Tasks
- [ ] Error message for sign up page
- [ ] create a check in database
- [ ] database sends error message to sign up page
