### ISSUE TITLE
1 Story point - 5.1 Setup IDE

### ISSUE THREAD

**Issue by bluebous** [CSBSJU-CS330-F21/CSB-SJU-Student-Services#7]
As a developer, I want to setup tomcat in IntelliJ so that I can test code within the IDE

- [x] Download Tomcat onto each developer's computer #27 
- [x] Setup IntelliJ on each developers computer #28
- [x] setup a configuration in the IDE to run Tomcat with the project #29 

## Done Criteria
All project developers are set up to use tomcat for project development
