### ISSUE TITLE
8 Story Points - 1.6 Edit Products

### ISSUE THREAD

**Issue by kaylithulin** [CSBSJU-CS330-F21/CSB-SJU-Student-Services#71]
As a seller, I want to edit my products that are created so that I have the option to change if I need.

## Tasks
- [ ] add an option to edit listing on the table which displays the listing
- [ ] allow them to save changes
- [ ] add tests to JUnit 

## Done Criteria
The seller can successfully edit their product in the product table on the listing page and all JUnit tests run successfully
