### ISSUE TITLE
2.2 search backend

### ISSUE THREAD

**Issue by bluebous** [CSBSJU-CS330-F21/CSB-SJU-Student-Services#77]
As a buyer, I wish to search for the specific product/service I need through a search tab
## Tasks
- [ ] create UML design
- [ ] research how to format sql queries
- [ ] create objects to return from queries
- [ ] deliver returned objets to front end
- [ ] add JUnit testing
