### ISSUE TITLE
8 Story points - 10.1 Sort Products

### ISSUE THREAD

**Issue by ocollison** [CSBSJU-CS330-F21/CSB-SJU-Student-Services#8]
As a user, I wish to sort how listings are displayed to me

## Tasks
- [ ] Have dropdown menu on the page where users can choose how they want their listings sorted
- [ ] Add sorting parameters for likes, date added and price
- [ ] add tests to JUnit

## Done Criteria
I can sort all listings by likes, date added or price
