### ISSUE TITLE
3.9 Add Password Criteria in Sign Up 

### ISSUE THREAD

**Issue by dalv001** [CSBSJU-CS330-F21/CSB-SJU-Student-Services#94]
As a developer, you would want your users to create an account with the appropriate sign up credentials to unsure secure accounts.

## Tasks
- [ ] Add a label to the sign up page, with password instruction
- [ ] If crediatntials don't pass then, alert user 
- [ ] if so then account created, and add it to the database

## Done 
User can successfully and securely create an account that will stored in the database, and will be able to login in the future with credentials he/she/they have created.
