### ISSUE TITLE
2 Story Points - 3.2.1 Password Criteria

### ISSUE THREAD

**Issue by kaylithulin** [CSBSJU-CS330-F21/CSB-SJU-Student-Services#96]
As a User, I want to know what the password criteria is so that I can successfully create an account and sign up. 

## Tasks
- [x] create label showing password criteria on sign up page
- [x] already have errors for bad passwords
- [x] already saves good passwords to database

## Done Criteria
User successfully sees the password criteria on sign up page, along with errors for bad passwords
